image: maven:3-openjdk-17

stages:
  - compile
  - test
  - build
  - deploy

mvn compile:
  stage: compile
  script:
    - export DB_HOST=$DB_HOST
    - export DB_PORT=$DB_PORT
    - export DB_NAME=$DB_NAME
    - export DB_USER=$DB_USER
    - export DB_PASSWORD=$DB_PASSWORD
    - export KEYCLOAK_BASE_URL=$KEYCLOAK_BASE_URL
    - export KEYCLOAK_REALM=$KEYCLOAK_REALM_PROD
    - export KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID_PROD
    - export KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET_PROD
    - export KEYCLOAK_MANAGER_USERNAME=$KEYCLOAK_MANAGER_USERNAME_PROD
    - export KEYCLOAK_MANAGER_PASSWORD=$KEYCLOAK_MANAGER_PASSWORD_PROD
    - export SMTP_USER=$SMTP_USER
    - export SMTP_PASSWORD=$SMTP_PASSWORD
    - mvn compile
mvn test:
  stage: test
  script:
    - export KEYCLOAK_BASE_URL=$KEYCLOAK_BASE_URL
    - export KEYCLOAK_REALM=$KEYCLOAK_REALM_TEST
    - export KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID_TEST
    - export KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET_TEST
    - export KEYCLOAK_MANAGER_USERNAME=$KEYCLOAK_MANAGER_USERNAME_TEST
    - export KEYCLOAK_MANAGER_PASSWORD=$KEYCLOAK_MANAGER_PASSWORD_TEST
    - export SMTP_USER=$SMTP_USER
    - export SMTP_PASSWORD=$SMTP_PASSWORD
    - mvn test

mvn package:
  stage: build
  script:
    - export DB_HOST=$DB_HOST
    - export DB_PORT=$DB_PORT
    - export DB_NAME=$DB_NAME
    - export DB_USER=$DB_USER
    - export DB_PASSWORD=$DB_PASSWORD
    - export KEYCLOAK_BASE_URL=$KEYCLOAK_BASE_URL
    - export KEYCLOAK_REALM=$KEYCLOAK_REALM_PROD
    - export KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID_PROD
    - export KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET_PROD
    - export KEYCLOAK_MANAGER_USERNAME=$KEYCLOAK_MANAGER_USERNAME_PROD
    - export KEYCLOAK_MANAGER_PASSWORD=$KEYCLOAK_MANAGER_PASSWORD_PROD
    - export SMTP_USER=$SMTP_USER
    - export SMTP_PASSWORD=$SMTP_PASSWORD
    
    - mvn package
    - cp target/voice-pick*.jar ~
    - cp Dockerfile ~

sonarqube-check:
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - export KEYCLOAK_BASE_URL=$KEYCLOAK_BASE_URL
    - export KEYCLOAK_REALM=$KEYCLOAK_REALM_TEST
    - export KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID_TEST
    - export KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET_TEST
    - export KEYCLOAK_MANAGER_USERNAME=$KEYCLOAK_MANAGER_USERNAME_TEST
    - export KEYCLOAK_MANAGER_PASSWORD=$KEYCLOAK_MANAGER_PASSWORD_TEST
    - export SMTP_USER=$SMTP_USER
    - export SMTP_PASSWORD=$SMTP_PASSWORD
    - mvn verify sonar:sonar -Dsonar.projectKey=IDATA-2900-Group-1_voice-pick-backend_AYbLKMhd0vjnirPHhSYJ
  allow_failure: true
  only:
    - trunk

docker run:
  stage: deploy
  script:
    - cd ~
    - docker build -t bachelor-b .
    - docker rm -f bachelor-backend
    - docker run -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -e DB_NAME=$DB_NAME -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e KEYCLOAK_BASE_URL=$KEYCLOAK_BASE_URL -e KEYCLOAK_REALM=$KEYCLOAK_REALM_PROD -e KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID_PROD -e KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET_PROD -e KEYCLOAK_MANAGER_USERNAME=$KEYCLOAK_MANAGER_USERNAME_PROD -e KEYCLOAK_MANAGER_PASSWORD=$KEYCLOAK_MANAGER_PASSWORD_PROD -e SMTP_USER=$SMTP_USER -e SMTP_PASSWORD=$SMTP_PASSWORD -p 8080:8080 --restart unless-stopped -d --name bachelor-backend bachelor-b
  dependencies:
    - mvn package
  when: manual
