image: maven:3-openjdk-17

stages:
  - build

build:
  stage: build
  script:
    - export DB_HOST=$DB_HOST
    - export DB_PORT=$DB_PORT
    - export DB_NAME=$DB_NAME
    - export DB_USER=$DB_USER
    - export DB_PASSWORD=$DB_PASSWORD
    - mvn clean
    - mvn compile
    - mvn package
